EXAMPLE_FOLDERS := $(shell find ./examples -mindepth 1 -maxdepth 1 -type d -name "go-lessons-*" | sort -t '-' -k 3n)
EXAMPLE_FILES := $(shell find $(EXAMPLE_FOLDERS) -type f | sort -t '-' -k 3n)


.PHONY: install
install:
	for example_folder in $(EXAMPLE_FOLDERS); do \
		(cd $$example_folder && go install); \
	done

.PHONY: uninstall
uninstall:
	for example_folder in $(EXAMPLE_FOLDERS); do \
		rm "$$(go env GOPATH)/bin/$${example_folder#./examples/}"; \
	done

INDEX.md: $(EXAMPLE_FILES)
	echo '<!--- This file was automatically generated by `make INDEX.md` -->\n\n# Index of examples\n' > $@
	for example_folder in $(EXAMPLE_FOLDERS); do \
		echo "- [$${example_folder#./}/main.go]($${example_folder#./}/main.go): `go doc $$example_folder`" >> $@; \
	done